export const ACTION = {
  SONG: {
    FETCH_LIST: 'SONG/FETCH_LIST',
    FETCH_LIST_PENDING: 'SONG/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'SONG/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'SONG/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'SONG/FETCH_LIST_END',
  },

  PLAYLIST: {
    FETCH_LIST: 'PLAYLIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'PLAYLIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'PLAYLIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'PLAYLIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'PLAYLIST/FETCH_LIST_END',
  },

  ALBUM: {
    FETCH_LIST: 'ALBUM/FETCH_LIST',
    FETCH_LIST_PENDING: 'ALBUM/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ALBUM/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ALBUM/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ALBUM/FETCH_LIST_END',
  },

  ARTIST: {
    FETCH_LIST: 'ARTIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'ARTIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ARTIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ARTIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ARTIST/FETCH_LIST_END',
  },

  ACTION: {
    IMPORT: 'ACTION/MPORT',
    IMPORT_PENDING: 'ACTION/IMPORT_PENDING',
    IMPORT_FULFILLED: 'ACTION/IMPORT_FULFILLED',
    IMPORT_REJECTED: 'ACTION/IMPORT_REJECTED',
    IMPORT_END: 'ACTION/IMPORT_END',

    EXPORT: 'ACTION/EXPORT',
    EXPORT_PENDING: 'ACTION/EXPORT_PENDING',
    EXPORT_FULFILLED: 'ACTION/EXPORT_FULFILLED',
    EXPORT_REJECTED: 'ACTION/EXPORT_REJECTED',
    EXPORT_END: 'ACTION/EXPORT_END',
  },
};
