export const ACTION = {
  PLAYLIST: {
    FETCH_LIST: 'PLAYLIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'PLAYLIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'PLAYLIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'PLAYLIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'PLAYLIST/FETCH_LIST_END',

    IMPORT: 'PLAYLIST/IMPORT',
    IMPORT_PENDING: 'PLAYLIST/IMPORT_PENDING',
    IMPORT_FULFILLED: 'PLAYLIST/IMPORT_FULFILLED',
    IMPORT_REJECTED: 'PLAYLIST/IMPORT_REJECTED',
    IMPORT_END: 'PLAYLIST/IMPORT_END',
  },

  ALBUM: {
    FETCH_LIST: 'ALBUM/FETCH_LIST',
    FETCH_LIST_PENDING: 'ALBUM/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ALBUM/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ALBUM/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ALBUM/FETCH_LIST_END',

    IMPORT: 'ALBUM/IMPORT',
    IMPORT_PENDING: 'ALBUM/IMPORT_PENDING',
    IMPORT_FULFILLED: 'ALBUM/IMPORT_FULFILLED',
    IMPORT_REJECTED: 'ALBUM/IMPORT_REJECTED',
    IMPORT_END: 'ALBUM/IMPORT_END',
  },

  ARTIST: {
    FETCH_LIST: 'ARTIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'ARTIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ARTIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ARTIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ARTIST/FETCH_LIST_END',

    IMPORT: 'ARTIST/IMPORT',
    IMPORT_PENDING: 'ARTIST/IMPORT_PENDING',
    IMPORT_FULFILLED: 'ARTIST/IMPORT_FULFILLED',
    IMPORT_REJECTED: 'ARTIST/IMPORT_REJECTED',
    IMPORT_END: 'ARTIST/IMPORT_END',
  }
};
