export const ACTION = {
  PLAYLIST: {
    FETCH_LIST: 'PLAYLIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'PLAYLIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'PLAYLIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'PLAYLIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'PLAYLIST/FETCH_LIST_END',
  },

  ALBUM: {
    FETCH_LIST: 'ALBUM/FETCH_LIST',
    FETCH_LIST_PENDING: 'ALBUM/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ALBUM/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ALBUM/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ALBUM/FETCH_LIST_END',
  },

  ARTIST: {
    FETCH_LIST: 'ARTIST/FETCH_LIST',
    FETCH_LIST_PENDING: 'ARTIST/FETCH_LIST_PENDING',
    FETCH_LIST_FULFILLED: 'ARTIST/FETCH_LIST_FULFILLED',
    FETCH_LIST_REJECTED: 'ARTIST/FETCH_LIST_REJECTED',
    FETCH_LIST_END: 'ARTIST/FETCH_LIST_END',
  },

  IMPORT: 'IMPORT',
  IMPORT_PENDING: 'IMPORT_PENDING',
  IMPORT_FULFILLED: 'IMPORT_FULFILLED',
  IMPORT_REJECTED: 'IMPORT_REJECTED',
  IMPORT_END: 'IMPORT_END',
};
